openapi: 3.0.0
info:
  title: Risk Management API
  version: 1.0.0
  description: API for managing risks, including retrieving, creating, and viewing individual risks.
servers:
  - url: /v1
paths:
  /risks:
    get:
      summary: Retrieve a list of Risks
      responses:
        '200':
          description: A list of Risks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Risk'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      summary: Create a new Risk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskCreate'
      responses:
        '201':
          description: Risk created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risk'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /risks/{id}:
    get:
      summary: Retrieve an individual Risk
      parameters:
        - name: id
          in: path
          required: true
          description: The UUID of the Risk to retrieve.
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Risk retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risk'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

components:
  schemas:
    Risk:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The auto-generated UUID of the Risk.
        state:
          type: string
          enum: [open, closed, accepted, investigating]
          description: The state of the Risk.
        title:
          type: string
          description: The title of the Risk.
        description:
          type: string
          description: The description of the Risk.
      required:
        - id
        - state
        - title
        - description

    RiskCreate:
      type: object
      properties:
        state:
          type: string
          enum: [open, closed, accepted, investigating]
          description: The state of the Risk (required).
        title:
          type: string
          description: The title of the Risk.
        description:
          type: string
          description: The description of the Risk.
      required:
        - state
        - title
        - description
